name: Mythril security checks

on:
  - pull_request

jobs:
  perform-mythril-checks:
    runs-on: ubuntu-latest
    container: mythril/myth
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install node dependencies
      run: yarn install

    - name: Run mythril/myth tool
      run: CI=1 yarn run flatten && yarn run mythril-security-checks
